### ISSUE TITLE
[Linux] Undefined symbols error

### ISSUE THREAD

**Issue by UsrLightmann** [DragonBuild/dragon#85] opened 2021-09-03 01:13 UTC
Possible duplicate of #76.

`if(@available(iOS 13, *))` causes the following error for both arm64 and arm64e:

```
Undefined symbols for architecture arm64e:
  "___isOSVersionAtLeast", referenced from:
      __ZL66_logos_method$Widgets_13$WGWidgetHostingViewController$viewDidLoadP29WGWidgetHostingViewControllerP13objc_selector in Tweak.xm.mm.o
```

Example usage: [here](https://github.com/UsrLightmann/Aeaea/blob/715a4f09d3a3309add9598fe43c05ccdec12fdd4/Tweak.xm#L854) 

Note: swapping out the contents of `iPhoneOS.sdk` in `~/.dragon/sdks/` with another patched sdk does _not_ resolve the issue, at least for me.

**Comment by KritantaDev** [comment] 2021-09-13 21:29
closed as duplicate of #76

**Closed by KritantaDev** 2021-09-13 21:29 UTC
